[package]
name = "tf-tags"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tf-core.workspace = true
lofty = { workspace = true }
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile = "3"
serde_json.workspace = true
